config/routes.rb
Rails.application.routes.draw do
  
  get "/" => "home#top"
  get "about" => "home#about"
  
  get "signup" => "users#new"
get "posts/contact"=>"posts#contact"
post "posts/contact_create" => "posts#contact_create"

  resources :users
  

  resources :posts do
    get 'contact'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    validates :plan_name, presence: true
    mount_uploader :image, ImageUploader
end

app/models/satoshi.rb
class Satoshi < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
#    validates:name,{presence:true, uniqueness:true}
#    validates:email, {presence:true, uniqueness:true}
  has_many :posts
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html: "hello, world!"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @users = User.all
  end
  
  def about
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts= Post.all.order(created_at: :desc)
  end
  
  def show
    @post = Post.find_by(id:params[:id])
    @user = @post.user
    @chat=Chat.new(chat:params[:chat])
    @chat.save
    @chats=Chat.all.order(created_at: :desc)
  end
  
  def new
    @post = Post.new
  end 
  
  def create
    user = User.find(1)
    @post = user.posts.build(post_params)
  
    if @post.save
      redirect_to posts_path and return
    end
    
    render :new
  end
  
  def contact
  end
  
  def contact_create
    redirect_to("/posts/contact")
  end

  private
  def post_params
    params.require(:post).permit(:plan_name, :content, :image)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user=User.new(user_params)
    # 保存が成功したかどうかで条件分岐をしてください
    if @user.save
      flash[:notice] = "ユーザー登録が完了しました"
      redirect_to("/")
    else
      render("users/new")
    end
  end
  
  def show
    @user = User.find_by(id:params[:id])
    @post = Post.find_by(id:params[:id])
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/about.html.erb
<div class="main top-main">
  <div class="top-message">
    <h2>本サービスの説明</h2>
    <p>自分だけのツアーを作成、提案することができ、実現できます！
        他では見つけることができない様々なプランを検索できます！</p>
  <p><img src="about.jpg"></p></div>
</div>

app/views/home/top.html.1.erb
<!--header start here-->
<div class="banner">
		<div class="top-nav">
	        <div class="container">
			<div class="navbar-header">
	   			 <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
	                <span class="sr-only">Toggle navigation</span>
	                <span class="icon-bar"></span>
	                <span class
	                ="icon-bar"></span>
	                <span class="icon-bar"></span>
                </button>
              </div>
	   			<div id="navbar" class="navbar-collapse collapse">
	              <ul class="nav navbar-nav">
	                  <li><a href="index.html" class="active">Home</a></li>
					  <li><a href="#about"  class="scroll">About</a></li>
					   <li><a href="#guide"  class="scroll">Guides</a></li>
					   <li><a href="#tour"  class="scroll">Tours</a></li>
					   <li><a href="#new" class="scroll">Create</a></li>
					   <li><a href="#signup"  class="scroll">Signup</a></li>
	              </ul>
	            </div>
              </div>
			</div>
				<div class="container">
	<div class="w3-agile-logo">
	<div class=" head-wl">
		<div class="headder-w3">
		<h1><a href="index.html">CasualTrip</a></h1>
		</div>
		<div class=" tele">
		<p><span  class="fa fa-phone" aria-hidden="true"></span> + 81 80 5871 3359</p>
		 <h6>Tokyo</h6>
		</div>
		<div class="clearfix"> </div>
		</div>
	</div>
	<div class="w3layouts-text">
					<h2>Deep and Unique Trip <span>for you</span></h2>
					<div class="border"></div>
					<p>Guides can realize your original trips</p>
					<p>Travellers can find deep and unique trips</p>
					
					
				</div>
				</div>
			</div>
<!--header strat here-->
<!-- modal -->
		<div class="modal about-modal fade" id="myModal" tabindex="-1" role="dialog">
			<div class="modal-dialog" role="document">
				<div class="modal-content">
					<div class="modal-header"> 
						<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>						
						<h4 class="modal-title">Dream Travel</h4>
					</div> 
					<div class="modal-body">
						<div class="agileits-w3layouts-info">
							<img src="sun-2298961.jpg" alt="" />
							<p>survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- //modal -->
	<!-- about-top -->
	<div class="about" id="about">
		<!-- container -->
		<div class="container">
			<div class="about-info">
				<h3>About Us</h3>
			</div>
			<div class="about-top-grids">
				<div class="col-md-8 about-top-grid">
					<h4>What Are we
					</h4>
					<p>Founded at Programming Bootscamp2017 and based in TokyoTech, Tokyo, CasualTrip is a trusted community marketplace for people to list, discover, and book unique travels in Japan — online or from a mobile phone or tablet.
Whether taking bath with wild monkeys in hot spring, climbing up the Mt.Fuji in for sunrise, or experiencing Japanese traditional tea cultures, CasualTrip connects travellers to unique travel experiences. CasualTrip is the easiest way for people to make original trip plans or find these unique trips. 
			     </p>
				</div>
				<div class="col-md-4 about-top-grid " >
					<img src="images/m1.jpg" alt="" />
				</div>
				<div class="clearfix"> </div>
			</div>
		
		
			
	<!-- //about-top -->
		
			<!-- team-->
	<div class="team agileits" id="guide">
	<div class="team-info">
		<div class="container">	 
			<div class="team-row">
				<h3 class="agile-title">Guides</h3> 
				<p>Find your own tour guides</p>
				<div class="col-md-3 team-grids">
					<div class="team-agile-img"> 
					
					<%= @users.each do |user| %>
						<a href="#"><img src="images/t#{user.id}.jpg" alt="img"></a>
						<div class="view-caption">
							<div class="w3ls-info">
								
								<h4><%= link_to("user.name", user_path(User.first)) %></h4> 
							</div>
						</div>  
						<% end %>
						
					</div>
				</div>					
				<div class="col-md-3 team-grids">
					<div class="team-agile-img"> 
						<a href="#"><img src="images/t2.jpg" alt="img"></a>
						<div class="view-caption">
							<div class="w3ls-info">
								<h4>Kanae </h4> 
							</div>
						
						</div>    
					</div>
				</div>
				<div class="col-md-3 team-grids">
					<div class="team-agile-img"> 
						<a href="#"><img src="images/t3.jpg" alt="img"></a>
						<div class="view-caption">
							<div class="w3ls-info">
								<h4>Haruki</h4> 
							</div>
							
						</div>    
					</div>
				</div>
				<div class="col-md-3 team-grids">
					<div class="team-agile-img"> 
						<a href="#"><img src="images/t4.jpg" alt="img"></a>
						<div class="view-caption">
							<div class="w3ls-info">
								<h4>Keisuke</h4> 
							</div>
							
						</div>    
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
</div>
<!-- //team -->
	
  
<!-- gallery -->
<div id="tour" class="gallery">
	<div class="container">
		<div class="gallery-info">
			<h3 class="title">Tours
			<div class="w3-button">
				 <%= link_to 'All tours', posts_path %>
			</div>
			</h3>
			
			<div class="col-md-4 gallery-grids">
				<a href="images/g1.jpg" class="gallery-box" data-lightbox="example-set" data-title="">
					<img src="images/g1.jpg" alt="" class="img-responsive zoom-img">
				</a>
			</div>
			<div class="col-md-4 gallery-grids">
				<a href="images/g2.jpg" class="gallery-box" data-lightbox="example-set" data-title="">
					<img src="images/g2.jpg" alt="" class="img-responsive zoom-img">
				</a>
			</div>
			<div class="col-md-4 gallery-grids">
				<a href="images/g3.jpg" class="gallery-box" data-lightbox="example-set" data-title="">
					<img src="images/g3.jpg" alt="" class="img-responsive zoom-img">
				</a>
			</div>

			<div class="col-md-6 gallery-grids grid-mdl">
				<a href="images/g4.jpg" class="gallery-box" data-lightbox="example-set" data-title="">
					<img src="images/g4.jpg" alt="" class="img-responsive zoom-img">
				</a>
			</div>
			<div class="col-md-6 gallery-grids grid-mdl">
				<a href="images/g5.jpg" class="gallery-box" data-lightbox="example-set" data-title="">
					<img src="images/g5.jpg" alt="" class="img-responsive zoom-img">
				</a>
			</div>
			<div class="clearfix"></div>
		</div>
		
	</div>
</div>
<!-- //gallery -->
<!--contact -->
	<div class="contact" id="contact">
		<div class="container">	
  <h3>CONTACT US</h3>		
			<div class="contact-form">
			  
				<p>When you have any questions, please fill out below form and contact us</p>
				<form action="#" method="post">
					<div class="col-md-6 form-left" >
						<input type="text" placeholder="Name" required="">
					</div>
					<div class="col-md-6 form-right ">
						<input class="email" type="email" placeholder="Email" required="">
					</div>
					<div class="clearfix"> </div>
					<input  type="text" placeholder="Phone" required="">
					<textarea placeholder="Message" required=""></textarea>
					<input type="submit" value="SUBMIT" >
				</form>
			</div>
		</div>
	</div>		
	<!--//contact -->

app/views/home/top.html.erb
<!--header start here-->
<div class="banner">
		<div class="top-nav">
	        <div class="container">
			<div class="navbar-header">
	   			 <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
	                <span class="sr-only">Toggle navigation</span>
	                <span class="icon-bar"></span>
	                <span class
	                ="icon-bar"></span>
	                <span class="icon-bar"></span>
                </button>
              </div>
	   			<div id="navbar" class="navbar-collapse collapse">
	              <ul class="nav navbar-nav">
	                  <li><a href="index.html" class="active">Home</a></li>
					  <li><a href="#about"  class="scroll">About</a></li>
					   <li><a href="#guide"  class="scroll">Guides</a></li>
					   <li><a href="#tour"  class="scroll">Tours</a></li>
					   <li><a href="#new" class="scroll">Create</a></li>
					   <li><a href="#signup"  class="scroll">Signup</a></li>
	              </ul>
	            </div>
              </div>
			</div>
				<div class="container">
	<div class="w3-agile-logo">
	<div class=" head-wl">
		<div class="headder-w3">
		<h1><a href="index.html">CasualTrip</a></h1>
		</div>
		<div class=" tele">
		<p><span  class="fa fa-phone" aria-hidden="true"></span> + 81 80 5871 3359</p>
		 <h6>Tokyo</h6>
		</div>
		<div class="clearfix"> </div>
		</div>
	</div>
	<div class="w3layouts-text">
					<h2>Deep and Unique Trip <span>for you</span></h2>
					<div class="border"></div>
					<p>Guides can realize your original trips</p>
					<p>Travellers can find deep and unique trips</p>
					
					
				</div>
				</div>
			</div>
<!--header strat here-->
<!-- modal -->
		<div class="modal about-modal fade" id="myModal" tabindex="-1" role="dialog">
			<div class="modal-dialog" role="document">
				<div class="modal-content">
					<div class="modal-header"> 
						<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>						
						<h4 class="modal-title">Dream Travel</h4>
					</div> 
					<div class="modal-body">
						<div class="agileits-w3layouts-info">
							<img src="sun-2298961.jpg" alt="" />
							<p>survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- //modal -->
	<!-- about-top -->
	<div class="about" id="about">
		<!-- container -->
		<div class="container">
			<div class="about-info">
				<h3>About Us</h3>
			</div>
			<div class="about-top-grids">
				<div class="col-md-8 about-top-grid">
					<h4>What Are we
					</h4>
					<p>Founded at Programming Bootscamp2017 and based in TokyoTech, Tokyo, CasualTrip is a trusted community marketplace for people to list, discover, and book unique travels in Japan — online or from a mobile phone or tablet.
Whether a traditional bar for a night, a Japanese castle for sightseeing, or national museums for studying, CasualTrip connects people to unique travel experiences. CasualTrip is the easiest way for people to make original trip plans or find these unique trips. 
			     </p>
				</div>
				<div class="col-md-4 about-top-grid " >
					<img src="images/m1.jpg" alt="" />
				</div>
				<div class="clearfix"> </div>
			</div>
		
		
			
	<!-- //about-top -->
		
			<!-- team-->
	<div class="team agileits" id="guide">
	<div class="team-info">
		<div class="container">	 
			<div class="team-row">
				<h3 class="agile-title">Guides</h3> 
				<div class="col-md-3 team-grids">
					<div class="team-agile-img"> 
						<a href="#"><img src="images/t1.jpg" alt="img"></a>
						<div class="view-caption">
							<div class="w3ls-info">
								<h4>Shinnosuke</h4> 
							</div>
							<ul>
								<li><a href="#"><span class="fa fa-facebook"></span></a></li>
								<li><a href="#"><span class="fa fa-twitter"></span></a></li>
								<li><a href="#"><span class="fa fa-google-plus"></span></a></li>
							</ul>
						</div>    
					</div>
				</div>					
				<div class="col-md-3 team-grids">
					<div class="team-agile-img"> 
						<a href="#"><img src="images/t2.jpg" alt="img"></a>
						<div class="view-caption">
							<div class="w3ls-info">
								<h4>Kanae </h4> 
							</div>
							<ul>
								<li><a href="#"><span class="fa fa-facebook"></span></a></li>
								<li><a href="#"><span class="fa fa-twitter"></span></a></li>
								<li><a href="#"><span class="fa fa-google-plus"></span></a></li>
							</ul>
						</div>    
					</div>
				</div>
				<div class="col-md-3 team-grids">
					<div class="team-agile-img"> 
						<a href="#"><img src="images/t3.jpg" alt="img"></a>
						<div class="view-caption">
							<div class="w3ls-info">
								<h4>Haruki</h4> 
							</div>
							<ul>
								<li><a href="#"><span class="fa fa-facebook"></span></a></li>
								<li><a href="#"><span class="fa fa-twitter"></span></a></li>
								<li><a href="#"><span class="fa fa-google-plus"></span></a></li>
							</ul>
						</div>    
					</div>
				</div>
				<div class="col-md-3 team-grids">
					<div class="team-agile-img"> 
						<a href="#"><img src="images/t4.jpg" alt="img"></a>
						<div class="view-caption">
							<div class="w3ls-info">
								<h4>Keisuke</h4> 
							</div>
							<ul>
								<li><a href="#"><span class="fa fa-facebook"></span></a></li>
								<li><a href="#"><span class="fa fa-twitter"></span></a></li>
								<li><a href="#"><span class="fa fa-google-plus"></span></a></li>
							</ul>
						</div>    
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
</div>
<!-- //team -->
	
  
<!-- gallery -->
<div id="tour" class="gallery">
	<div class="container">
		<div class="gallery-info">
			<h3 class="title">Tours
			<div class="w3-button">
				 <%= link_to 'All tours', posts_path %>
			</div>
			</h3>
			
			<div class="col-md-4 gallery-grids">
				<a href="images/g1.jpg" class="gallery-box" data-lightbox="example-set" data-title="">
					<img src="images/g1.jpg" alt="" class="img-responsive zoom-img">
				</a>
			</div>
			<div class="col-md-4 gallery-grids">
				<a href="images/g2.jpg" class="gallery-box" data-lightbox="example-set" data-title="">
					<img src="images/g2.jpg" alt="" class="img-responsive zoom-img">
				</a>
			</div>
			<div class="col-md-4 gallery-grids">
				<a href="images/g3.jpg" class="gallery-box" data-lightbox="example-set" data-title="">
					<img src="images/g3.jpg" alt="" class="img-responsive zoom-img">
				</a>
			</div>

			<div class="col-md-6 gallery-grids grid-mdl">
				<a href="images/g4.jpg" class="gallery-box" data-lightbox="example-set" data-title="">
					<img src="images/g4.jpg" alt="" class="img-responsive zoom-img">
				</a>
			</div>
			<div class="col-md-6 gallery-grids grid-mdl">
				<a href="images/g5.jpg" class="gallery-box" data-lightbox="example-set" data-title="">
					<img src="images/g5.jpg" alt="" class="img-responsive zoom-img">
				</a>
			</div>
			<div class="clearfix"></div>
		</div>
		
	</div>
</div>
<!-- //gallery -->
<!--contact -->
	<div class="contact" id="contact">
		<div class="container">	
  <h3>CONTACT US</h3>		
			<div class="contact-form">
			  
				<p>When you have any questions, please fill out below form and contact us</p>
				<form action="#" method="post">
					<div class="col-md-6 form-left" >
						<input type="text" placeholder="Name" required="">
					</div>
					<div class="col-md-6 form-right ">
						<input class="email" type="email" placeholder="Email" required="">
					</div>
					<div class="clearfix"> </div>
					<input  type="text" placeholder="Phone" required="">
					<textarea placeholder="Message" required=""></textarea>
					<input type="submit" value="SUBMIT" >
				</form>
			</div>
		</div>
	</div>		
	<!--//contact -->

app/views/layouts/application.html.erb
<!--A Design by W3layouts
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html lang="en">
<head>
<title>Dream Travel a Travel Category Bootstrap responsive Website Template  | Home :: w3layouts</title>
<!--meta tags -->
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="keywords" content="Dream Travel Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
		function hideURLbar(){ window.scrollTo(0,1); } </script>
<!--//meta tags ends here-->
<!--booststrap-->
<link href="/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" >
 
<!--//booststrap end-->

<!-- font-awesome icons -->
   <link rel="stylesheet" href="/css/font-awesome.min.css" />

<!-- //font-awesome icons -->
<!--stylesheets-->
<link href="/css/style.css" rel='stylesheet' type='text/css' media="all">
<!--//style sheet end here-->
<link rel="stylesheet" href="/css/lightbox.css">
<link href="//fonts.googleapis.com/css?family=Encode+Sans+Condensed:300,400,500,600,700" rel="stylesheet">
<link href="//fonts.googleapis.com/css?family=Abel" rel="stylesheet">
</head>
<body>    

<% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
<% end %>


<%= yield %>
 
<footer>
	<p>&copy;2017 Dream Travel. All Rights Reserved | Design by <a href="http://www.W3Layouts.com" target="_blank">W3Layouts</a></p>

  </footer>
<!-- Footer -->	
					
		<script type='text/javascript' src='js/jquery-2.2.3.min.js'></script>
		<!-- //js -->

<!--menu script-->
	<script src="js/bootstrap.min.js"></script>	
	<!-- gallery -->
<script src="js/lightbox-plus-jquery.min.js"></script> 
<!-- //gallery -->
<!-- OnScroll-Number-Increase-JavaScript -->
	<script type="text/javascript" src="js/numscroller-1.0.js"></script>
<!-- //OnScroll-Number-Increase-JavaScript -->
	<!-- start-smoth-scrolling -->
			<script type="text/javascript" src="js/move-top.js"></script>
			<script type="text/javascript" src="js/easing.js"></script>
			<script type="text/javascript">
				jQuery(document).ready(function($) {
					$(".scroll").click(function(event){		
						event.preventDefault();
						$('html,body').animate({scrollTop:$(this.hash).offset().top},900);
					});
				});
			</script>
		<!-- start-smoth-scrolling -->
	
		<!-- for-bottom-to-top smooth scrolling -->
			<script type="text/javascript">
				$(document).ready(function() {
				/*
					var defaults = {
					containerID: 'toTop', // fading element id
					containerHoverID: 'toTopHover', // fading element hover id
					scrollSpeed: 1200,
					easingType: 'linear' 
					};
				*/								
				$().UItoTop({ easingType: 'easeOutQuart' });
				});
			</script>
			<a href="#" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
		<!-- //for-bottom-to-top smooth scrolling -->
		
<!-- //js-scripts -->	


</body>
</html>		

app/views/posts/contact.html.erb
<div class= "posts-contact">
    <div class="about-info">
	  <h3>Contact</h3>
	</div>
            <%= form_tag("/posts/contact_create") do %>
      <div class="form">
        <div class="form-body">
          <textarea name="content"></textarea>
          <input type="submit" value="投稿">
        </div>
      </div>
    <% end %>
</div>

app/views/posts/index.html.erb
<!-- gallery -->
<div id="tour" class="gallery">
	<div class="container">
		<div class="gallery-info">
			<h3 class="title">All Tours</h3>
			
			<% @posts.each do |post|%>
        <div class="col-md-4 gallery-grids">
  				<%= link_to(post_path(post)) do %>
  				<% if post.image.thumb.present? %> 
  				  <%= image_tag post.image.thumb.url, class: "img-responsive zoom-img" %>
  				  <% end %>
  				  <%= link_to(post.plan_name, post_path(post)) %>
  				<% end %>
  				
  		</div>
      <% end %>
    </div>
	</div>
</div>
<!-- //gallery -->

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
    <div class="posts-create">
        <%= f.text_field :plan_name %>
        <%= f.text_area :content, rows: 10 %>
    　　<%= f.file_field :image %> 
    　　<%= f.submit '投稿' %>
    </div>
<% end %>

app/views/posts/show.html.erb
<!-- about-top -->
<div class="about" id="about">
  <!-- container -->
  <div class="container">
	<div class="about-info">
	  <h3>Tour Contents</h3>
	</div>
	<div class="about-top-grids">
	  <div class="col-md-8 about-top-grid">
		<% @post %>
	  </div>
	  <div class="col-md-4 about-top-grid " >
	    <img src="images/m1.jpg" alt="" />
	  </div>
	</div>
    <div class= "posts-show">
      <h2><%= @post.plan_name %></h2>
          <%= simple_format @post.content %> 
    </div>

    <div class="posts-contact-detail">
      <%= image_tag @post.image.thumb.url %>
    </div>

    <div class="chat-part"></div>
    <div>
      <%= link_to "ガイド", @user %>
    </div>
    <div class="posts-contact">
      <%= link_to("コンタクト","/posts/#{@post.id}/contact")%>    
    </div>
  </div>
</div>
<!-- //about-top -->

app/views/users/index.html.erb
<div class="users-index">
    <% @users.each do |user| %>
    <div>
    		<%= link_to user.name, user%>
    </div>
    <% end %>
</div>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
    <div class="posts-create">
        <p> ユーザー名</p>
        <%= f.text_field :name %>
        <p> メールアドレス</p>
        <%= f.text_area :email, rows: 10 %>
        <p> プロフィール画像</p>
　　    <%= f.file_field :image %> （画像用に追加したカラムの名前）
　　    <%= f.submit '新規登録' %>
    </div>
<% end %>

<% @user.errors.full_messages.each do |message| %>
          <div class="form-error">
            <%= message %>
          </div>
        <% end %>

</div>

app/views/users/show.html.erb
<!-- about-top -->
<div class="about" id="about">
  <!-- container -->
  <div class="container">
	<div class="about-info">
	  <h3>Tour Contents</h3>
	</div>
	<div class="about-top-grids">
	  <div class="col-md-8 about-top-grid">
		<% @user %>
	  </div>
	  <div class="col-md-4 about-top-grid " >
	    <img src="images/m1.jpg" alt="" />
	  </div>
	</div>
    <div class= "posts-show">
      <h2><%= @user.name %></h2>
          <%= simple_format @user.email %> 
    </div>

    <div class="posts-contact-detail">
      <%= image_tag @post.image.thumb.url %>
    </div>

    <div class="chat-part"></div>
    <div>
      <%= link_to "ガイド", @user %>
    </div>
    <div class="posts-contact">
      <%= link_to("コンタクト","/posts/#{@post.id}/contact")%>    
    </div>
  </div>
</div>
<!-- //about-top -->

<div class= "users-show">
    <%= @user.name %>

    <%= @user.created_at%>
</div>

<% @user.posts.each do |post| %>
  <%= link_to post.plan_name, post %>
<% end %>

<li class="new">
      <%= link_to "新規投稿", new_post_path %> <!--新規投稿へのリンク-->
</li>